#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v20
# autospec commit: f35655a
#
Name     : R-lmom
Version  : 3.2
Release  : 28
URL      : https://cran.r-project.org/src/contrib/lmom_3.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/lmom_3.2.tar.gz
Summary  : L-Moments
Group    : Development/Tools
License  : CPL-1.0
Requires: R-lmom-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
and trimmed L-moments of distributions and data samples; parameter
  estimation; L-moment ratio diagram; plot vs. quantiles of an
  extreme-value distribution.

%package lib
Summary: lib components for the R-lmom package.
Group: Libraries

%description lib
lib components for the R-lmom package.


%prep
%setup -q -n lmom
pushd ..
cp -a lmom buildavx2
popd
pushd ..
cp -a lmom buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1727793167

%install
export SOURCE_DATE_EPOCH=1727793167
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/lmom/CITATION
/usr/lib64/R/library/lmom/DESCRIPTION
/usr/lib64/R/library/lmom/INDEX
/usr/lib64/R/library/lmom/Meta/Rd.rds
/usr/lib64/R/library/lmom/Meta/features.rds
/usr/lib64/R/library/lmom/Meta/hsearch.rds
/usr/lib64/R/library/lmom/Meta/links.rds
/usr/lib64/R/library/lmom/Meta/nsInfo.rds
/usr/lib64/R/library/lmom/Meta/package.rds
/usr/lib64/R/library/lmom/NAMESPACE
/usr/lib64/R/library/lmom/NEWS
/usr/lib64/R/library/lmom/R/lmom
/usr/lib64/R/library/lmom/R/lmom.rdb
/usr/lib64/R/library/lmom/R/lmom.rdx
/usr/lib64/R/library/lmom/help/AnIndex
/usr/lib64/R/library/lmom/help/aliases.rds
/usr/lib64/R/library/lmom/help/lmom.rdb
/usr/lib64/R/library/lmom/help/lmom.rdx
/usr/lib64/R/library/lmom/help/paths.rds
/usr/lib64/R/library/lmom/html/00Index.html
/usr/lib64/R/library/lmom/html/R.css
/usr/lib64/R/library/lmom/lmom-manual.pdf

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/lmom/libs/lmom.so
/V4/usr/lib64/R/library/lmom/libs/lmom.so
/usr/lib64/R/library/lmom/libs/lmom.so
